### PR TITLE
Update csv_encoder.ex

### PR DESCRIPTION
**Pull request by jack-s9**
* Add code formatting around iex example for Crawly.Pipelines.CSVEncoder docs

### CODE REVIEW

**Comment by Ziinc** [comment]
@jack-s9 thanks for the fix, code indentation does not actually require backticks, see here https://hexdocs.pm/elixir/1.13/writing-documentation.html

could you remove the backticks and add in the additional line after the header? i think the parser requires a newline.

Checks are failing are on me, will fix. thanks for contrib!

**Comment by jack-s9** [comment]
I made the change to remove the backticks.  I'm pushing changes from the GitHub web interface and wasn't sure how to squash my commits.  Let me know if you need any other changes.

**Comment by oltarasenko** [comment]
Hey. As far as I see, it failed on --check-formatted step. Could you please format the code so I can merge it? @jack-s9

**Review by Ziinc — APPROVED** [review]

**Review by Ziinc — APPROVED** [review]

**Comment by Ziinc** [comment]
@oltarasenko coveralls uploading doesn't work for PRs, for some reason.

**Pull request closed without merging**
